spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost/muli-module-demo?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #连接池配置
      filters: stat,wall,log4j
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
#        url-pattern:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#        session-stat-enable:
#        session-stat-max-count:
#        principal-session-name:
#        principal-cookie-name:
#        profile-enable:
      stat-view-servlet:
        enabled: true
#        url-pattern:
#        reset-enable:
        login-username: username
        login-password: password
#        allow:
#        deny:

  redis:
    host: 127.0.0.1
    port: 6379

  http:
        # multipart config
    multipart:
      enabled: true
      location: /home/earthchen/study/xxx
      file-size-threshold: 5MB
      max-request-size: 20MB




mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.earthchen.spring.boot.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


# 七牛云配置
qiniu:
  accessKey: BjSrFopaG-Qpsbj6tiAOvRKTdBecktBYYYw9B9bE
  secretKey: xxxx
  bucket: search-house
  cdnPrefix: p5jbnmadg.bkt.clouddn.com

elasticsearch:
  esHost: 127.0.0.1
  esPort: 9300
  esClusterName: earthchen
